version: '3'
services: 
  elixir:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    volumes: 
      - .:/usr/source/myapp:delegated
    working_dir: "/usr/source/myapp"      
    #command: "iex -S mix"