#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# redirecting the admin index
homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /admin/events
    permanent: true

admin:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /admin/events
    permanent: true
