version: '3.4'

services:
  api:
    build:
      context: ./backend
      args: 
        UID: ${UID}
        GID: ${GID}

    depends_on:
    - mongo
    volumes:
    - ./backend:/var/www/app:rw,cached
    ports:
    - "8087:8000"
    environment:
      MONGODB_URL: mongodb://root:example@mongo
      MONGODB_DB: ethickets
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  elixir:
    build:
      context: ethereum_service
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    volumes: 
      - ./ethereum_service:/usr/source/myapp:delegated
    working_dir: "/usr/source/myapp"      
    #command: "iex -S mix"
