version: '3.4'

services:
  api:
    build:
      context: ./backend
      args: 
        UID: ${UID}
        GID: ${GID}

    depends_on:
    - mongo
    volumes:
    - ./backend:/var/www/app:rw,cached
    ports:
    - "8087:8000"
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
